[DISCO-2427] Metrics ADR and ADR Template
mozilla-services/consvc-shepherd pull request #137
Opened 2023-06-08 19:39 UTC by taddes

## References

JIRA: [DISCO-2427](https://mozilla-hub.atlassian.net/browse/DISCO-2427)
GitHub: [#136 ](https://github.com/mozilla-services/consvc-shepherd/issues/136)

## Description
Create an ADR to capture the benefits and decision behind using Markus as our metrics client library, as discussed by the team and sourced from other Mozilla teams. Can be used for future reference given the possibility of using the library on other projects.

## PR Review Checklist

_Put an `x` in the boxes that apply_

- [ ] This PR conforms to the [Contribution Guidelines](https://github.com/mozilla-services/consvc-shepherd/blob/main/CONTRIBUTING.md).
- [ ] The PR title starts with the JIRA issue reference, format `[DISCO-####]`, and has the same title (if applicable).
- [ ] [Documentation](https://github.com/mozilla-services/consvc-shepherd/tree/main/docs) has been updated (if applicable).
- [ ] Functional and performance test coverage has been expanded and maintained (if applicable).

2023-06-12 14:46 UTC, hackebrot requested changes
Hi @taddes! 👋🏻

Thank you for creating this!

I've added my comments inline.

2023-06-12 14:46 UTC, hackebrot commented on docs/adr/0000-metrics-client-for-shepherd.md
> +## Considered Options
Links to the PyPI sites for these packages would be helpful.

2023-06-12 14:46 UTC, hackebrot commented on docs/adr/0000-metrics-client-for-shepherd.md
> +Most StatsD libraries are simple, in that the core functions of calling an increment, gauge, timer and histogram.  Markus matches this simplicity with added flexibility, in that you can define tags a
See above comment about using the word "simple".

2023-06-12 14:46 UTC, hackebrot commented on docs/adr/0000-metrics-client-for-shepherd.md
> +* Built-in DogStatsD though backend.
```suggestion
* Built-in DogStatsD through backend.
```

2023-06-12 14:46 UTC, hackebrot commented on docs/adr/0000-metrics-client-for-shepherd.md
> +## Decision Drivers
This list seems to be missing the async/sync point you made on Slack.

Another important driver with respect to a Rapid Release Model is that it's easier for engineers to contribute and ship code to production when we're we’re using the same tool (library/framework) for the same task (metrics collection) for similar projects (Python services developed and owned by this team).

2023-06-12 16:10 UTC, taddes commented
Thanks for the thoughtful review and useful comments @hackebrot , I've made the recommended changes. Glad we'll have this to reference in our ongoing discussions regarding metrics.

2023-06-21 13:04 UTC, hackebrot requested changes
Thank you for addressing my comments, @taddes!

Added my feedback on the updated revision inline.

2023-06-21 14:09 UTC, taddes commented on docs/adr/0000-metrics-client-for-shepherd.md
> +Most StatsD libraries are not excessively complicated, in that the core functions of calling an increment, gauge, timer and histogram.  Markus matches this need with added flexibility, in that you ca
The examples below and the `Positive Consequences` section capture the benefits and exemplify the described Decision Outcome. I added an additional line describing why aiodogstatsd would be inappropriate given this exploration.

2023-06-21 14:54 UTC, Trinaa commented on docs/adr/0000-metrics-client-for-shepherd.md
> +**[Backends](https://markus.readthedocs.io/en/latest/backends.html)** - A significant feature Markus has over other libraries is the ability to define metrics backends. It comes with the `LoggingMetr
backend?

```suggestion
**[Backends](https://markus.readthedocs.io/en/latest/backends.html)** - A significant feature Markus has over other libraries is the ability to define metrics backends. It comes with the `LoggingMetrics`, `LoggingRollupMetrics`, `StatsdMetrics`, `DatadogMetrics`, `CloudwatchMetrics` by default, handling numerous configuration optimizations. You can also define your own backend.
```

2023-06-21 17:47 UTC, hackebrot requested changes

2023-06-21 17:47 UTC, hackebrot commented on docs/adr/0000-metrics-client-for-shepherd.md
> +**[Filters](https://markus.readthedocs.io/en/latest/filters.html)** - Markus lets you write filters to modify generated metrics on the fly. This allows infinite customization to drop or modify metric
Looks like something is missing here or the `Th` needs to be deleted.

2023-06-21 17:47 UTC, hackebrot commented on docs/adr/0000-metrics-client-for-shepherd.md
> +[pypi](https://pypi.org/project/markus/)
Python Package Index (PyPI). All lowercase is the URL. Would be good to get this updated throughout the doc.

```suggestion
[PyPI](https://pypi.org/project/markus/)
```

2023-06-21 17:47 UTC, hackebrot commented on docs/adr/0000-metrics-client-for-shepherd.md
> +
Unnecessary white-space.

2023-06-21 17:47 UTC, hackebrot commented on docs/adr/0000-metrics-client-for-shepherd.md
> +Shepherd is currently a minimal Django Admin application used to create and publish snapshots of advertiser settings of Sponsored Tiles. The recent expansion of the service through the Project Honeyc
Missing links for `[DISCO-2290]` and `[DISCO-2208]`.

2023-06-21 17:54 UTC, taddes commented on docs/adr/0000-metrics-client-for-shepherd.md
> +Shepherd is currently a minimal Django Admin application used to create and publish snapshots of advertiser settings of Sponsored Tiles. The recent expansion of the service through the Project Honeyc
I hadn't intended to add the links originally, as the urls point to our internal Jira boards and I didn't necessarily want that in a public repo. Anyone internal in Mozilla could use the project and number to view them, but I'm happy to add them.

2023-06-22 12:10 UTC, hackebrot approved these changes
Appreciate the work you've done on this ADR, @taddes! 🚀

2023-06-22 12:39 UTC, taddes commented
Thanks so much @hackebrot . Appreciate feedback and great that we can lean on this process to have well-documented technical decisions.

2023-06-22 12:40 UTC, merged