[DISCO-2420] enamed metrics methods
mozilla-services/consvc-shepherd pull request #141
Opened 2023-06-12 14:53 UTC by taddes

## References

JIRA: [DISCO-2420](https://mozilla-hub.atlassian.net/browse/DISCO-2420)
GitHub: [#139 ](https://github.com/mozilla-services/consvc-shepherd/issues/139)

## Description
There are a number of available customization options that can be implemented in the Django Admin page. This would remove some of the defaults in the UI/UX that default to Django and would allow for an improved UI with greater cohesion to the application.

## PR Review Checklist

_Put an `x` in the boxes that apply_

- [ ] This PR conforms to the [Contribution Guidelines](https://github.com/mozilla-services/consvc-shepherd/blob/main/CONTRIBUTING.md).
- [ ] The PR title starts with the JIRA issue reference, format `[DISCO-####]`, and has the same title (if applicable).
- [ ] [Documentation](https://github.com/mozilla-services/consvc-shepherd/tree/main/docs) has been updated (if applicable).
- [ ] Functional and performance test coverage has been expanded and maintained (if applicable).

2023-06-15 23:37 UTC, tiftran requested changes
Nice changes!

2023-06-15 23:37 UTC, tiftran commented on consvc_shepherd/admin.py
> +        return row
Good idea, but I don't think we need `to_dict()` for this. We could simplify this to something like:
```suggestion
 def partner_allocation(self, obj) -> str:
        """Partner allocation summary display column."""
        result = PartnerAllocation.objects.filter(allocation_position=obj).order_by(
            "-percentage"
        )
        row = ""
        for item in result:
            row += f"{item.partner.name}: {item.percentage}% "
        return row
```

2023-06-15 23:37 UTC, tiftran commented on consvc_shepherd/utils.py
> +    def incr(self, name: str, value: int = 1, tags: str | None = None) -> None:
sneaking renaming function names in here i see 😉

2023-06-15 23:41 UTC, tiftran commented on consvc_shepherd/admin.py
> +        return row
while we're at it, can we add ordering for `AllocationSettingAdmin` using "position"?

2023-06-16 02:07 UTC, taddes commented on consvc_shepherd/admin.py
> +        return row
Nice, that's a lot cleaner. Thx!

2023-06-16 19:10 UTC, taddes commented on consvc_shepherd/admin.py
> +        return row
Hi @tiftran . I did add one additional fallback to check for `NoneType` in the case that a partner is deleted. It will render 'Deleted Partner' and doesn't crash the application. When testing, if a partner is deleted, the `name` of the formerly allocated partner causes the rendering code to crash, so I just check for that in the loop. See below
```python
    def partner_allocation(self, obj) -> str: 
        """Partner allocation summary display column."""
        result = PartnerAllocation.objects.filter(allocation_position=obj).order_by(
            "-percentage"
        )
        row = ""
        for item in result:
            if not item.partner:
                row += f"Deleted Partner: {item.percentage}% "
            else:
                row += f"{item.partner.name}: {item.percentage}% "
        return row
```

<img width="1129" alt="Screen Shot 2023-06-16 at 3 05 30 PM" src="https://github.com/mozilla-services/consvc-shepherd/assets/35045299/bf6d29ee-8c94-41c5-a9e7-559f08ae0bc0">
<img width="983" alt="Screen Shot 2023-06-15 at 11 25 42 PM" src="https://github.com/mozilla-services/consvc-shepherd/assets/35045299/79d1915f-ff7a-4219-996f-b8751b13061b">

2023-06-16 23:33 UTC, tiftran commented on consvc_shepherd/admin.py
> +        return row
good catch

2023-06-16 23:33 UTC, tiftran approved these changes

2023-06-19 12:25 UTC, merged