[DISCO-2441] allocation setting validators and boundaries
mozilla-services/consvc-shepherd pull request #153
Opened 2023-07-10 11:49 UTC by taddes

## References

JIRA: [DISCO-2441](https://mozilla-hub.atlassian.net/browse/DISCO-2441)
GitHub: [#TODO](https://github.com/mozilla-services/consvc-shepherd/issues/TODO)

## Description
Adds some boundary checks to min and max values in admin console, does not by default show an extra input value when allocation already set, prevents the user from saving an allocation that is equal to 0, which is possible in admin and custom view at present.

<img width="774" alt="Screen Shot 2023-07-10 at 1 34 09 PM" src="https://github.com/mozilla-services/consvc-shepherd/assets/35045299/27faa400-4909-45de-9506-b01bac059a19">

<img width="604" alt="Screen Shot 2023-07-10 at 1 26 36 PM" src="https://github.com/mozilla-services/consvc-shepherd/assets/35045299/f5c51337-87e6-4532-b64a-4435ecc40278">

<img width="618" alt="Screen Shot 2023-07-10 at 1 25 53 PM" src="https://github.com/mozilla-services/consvc-shepherd/assets/35045299/45bee7ef-e9c1-485a-872b-26e81597eed5">

## PR Review Checklist

_Put an `x` in the boxes that apply_

- [ ] This PR conforms to the [Contribution Guidelines](https://github.com/mozilla-services/consvc-shepherd/blob/main/CONTRIBUTING.md).
- [ ] The PR title starts with the JIRA issue reference, format `[DISCO-####]`, and has the same title (if applicable).
- [ ] [Documentation](https://github.com/mozilla-services/consvc-shepherd/tree/main/docs) has been updated (if applicable).
- [ ] Functional and performance test coverage has been expanded and maintained (if applicable).

2023-07-10 16:55 UTC, tiftran requested changes
We allowed 0% on the firefox side, I _think_ it should be okay if we leave out a partner, but I would need to double check about that, but given it is okay, there's some comments below relating to this.

2023-07-10 16:55 UTC, tiftran commented on consvc_shepherd/admin.py
> +    extra = 0
I personally think leaving it is fine as is. Having a 1 there is just so that the partner form is already there when you create a new allocation. Since the allocation form is now moved out of the django admin, I foresee this admin form to be used only by engineers, so it's okay.

2023-07-10 16:55 UTC, tiftran commented on consvc_shepherd/forms.py
> +
I don't think we really need this changing [this](https://github.com/mozilla-services/consvc-shepherd/blob/main/consvc_shepherd/forms.py#L136) to 1 should be sufficient.
![Screenshot 2023-07-10 at 9 41 22 AM](https://github.com/mozilla-services/consvc-shepherd/assets/25379936/fa44824a-e43c-4b00-bd5d-aeb9b334be6d)

Future reference, I think it's best that we leave this `clean` method for validation related to the form as a whole and anything field specific in their own corresponding form specific `clean` methods

2023-07-10 16:55 UTC, tiftran commented on Makefile
> +	$(POETRY) run flake8 $(APP_DIRS) --ignore=E203,E302,E501,E701,W503
we won't need this given that we don't need the form validation below

2023-07-10 18:06 UTC, taddes commented on consvc_shepherd/admin.py
> +    extra = 0
Ok, wfm!

2023-07-11 23:08 UTC, tiftran requested changes

2023-07-11 23:08 UTC, tiftran commented on consvc_shepherd/tests/test_forms.py
> +        )
Can we move these into a diff Test Class they shouldn't be in the same class with the SnapshotForm. In addition, I don't think this is effectively testing out the form. Could we structure them such that we have 
```
# .... data setup

form = PartnerAllocationForm(<data>)
self.assertFalse(form.is_valid())
# ... assertions with form.errors


```

2023-07-12 13:50 UTC, taddes commented on consvc_shepherd/tests/test_forms.py
> +        )
Sure good call, thanks for the suggestion, I'll move it to its own class.

2023-07-21 17:20 UTC, tiftran reviewed
I've been flip flopping on this, and I think maybe it might be best to leave it as is for now . 
Since there are currently two partners at the moment and setting a partner to be 0 is harmless as firefox expects it, we also have validation to ensure 100% is allocated. We can revisit, if this becomes a problem when there are more partners.

I've left some fyis below

2023-07-21 17:20 UTC, tiftran commented on consvc_shepherd/tests/test_forms.py
> +        self.data_above: dict = {
So data for a form would correspond to its fields, in this case, the `PartnerAllocationForm` data fields would be `partner` and `percentage`.

If debugged and step into this, after calling `form.is_valid()` i believe `form.errors` would return some error messages stating that fields are required.

2023-07-21 18:17 UTC, closed without merging

2023-07-21 18:18 UTC, taddes commented
Holding off on merging until discussing broader UI features and possible explicit partner definition.