[DISCO-2531] GitHub landing page
mozilla-services/consvc-shepherd pull request #161
Opened 2023-07-24 15:35 UTC by taddes

## References

JIRA: [DISCO-2531](https://mozilla-hub.atlassian.net/browse/DISCO-2531)
GitHub: [#TODO](https://github.com/mozilla-services/consvc-shepherd/issues/TODO)

## Description
Add Shepherd landing page for GitHub

## PR Review Checklist

_Put an `x` in the boxes that apply_

- [ ] This PR conforms to the [Contribution Guidelines](https://github.com/mozilla-services/consvc-shepherd/blob/main/CONTRIBUTING.md).
- [ ] The PR title starts with the JIRA issue reference, format `[DISCO-####]`, and has the same title (if applicable).
- [ ] [Documentation](https://github.com/mozilla-services/consvc-shepherd/tree/main/docs) has been updated (if applicable).
- [ ] Functional and performance test coverage has been expanded and maintained (if applicable).

2023-07-26 02:05 UTC, mtbottle requested changes
The Quick Start Guide will need to be reworked a bit. In particular, there are too many "options" that it's providing users for their environment set up (which makes it not really "quick"). I'm not sure if you would prefer to have that as a separate ticket, or also just make the changes in this PR. I think [this comment](https://github.com/mozilla-services/contile/pull/614#discussion_r1268278020) is particularly relevant on stuff to fix for the guide.

Also, just a hint (in case you don't know about it), but you can use https://mermaid.live/edit to work on your architecture diagram with up-to-date preview! I find that it's easier to work this way, then copy it back into the documentation. I would be interested to hear if you're using another mermaid live updating platform!

2023-07-26 13:07 UTC, taddes commented on README.md
>  Merino and Contile. The settings managed here can be changed at runtime,
This was in this README when I moved it, so I know there is a hope for this one day, but agreed, it is a bit misleading at this point.

2023-07-26 14:21 UTC, taddes commented on docs/quickStart.md
> +or their EDB installer client.  Make sure to install version 14.7, or equivalent, and have
I'll make a note to talk with Tif about this, as to my knowledge, we both use this DB setup instead of Docker. We may need to make some revisions to the Docker setup given the progress on Shepherd. Why don't we leave this for now and I've made a note to revisit.  While setup with Postgres does work quite well, but we definitely want a smooth Docker option for sure. 👍

2023-07-26 14:27 UTC, taddes commented on docs/intro.md
> +Within Shepherd, users can make changes to Advertising Partners. A given Partner can have multiple advertisers in numerous geolocations, each with their own distinct domain.  Users can also define pa
This is great, thanks for sharing! Really insightful article on it.

2023-07-26 15:51 UTC, tiftran commented on docs/quickStart.md
> +or their EDB installer client.  Make sure to install version 14.7, or equivalent, and have
Sooo I don't actually use the DB setup anymore, currently running shepherd locally and db within docker. My perspective is that I don't think it really matters how we currently have shepherd set up. I think providing the easiest starting point for someone to set up should be sufficient and it would be up to them at that point to decide whatever variations they prefer. @taddes @mtbottle thoughts?

2023-07-26 17:25 UTC, mtbottle commented on docs/quickStart.md
> +or their EDB installer client.  Make sure to install version 14.7, or equivalent, and have
> I think providing the easiest starting point for someone to set up should be sufficient and it would be up to them at that point to decide whatever variations they prefer.

I would agree with that. I think we should go further and discourage variations. The reasons for this are:

1. Less experienced users may not have enough knowledge to know which set up is easier, especially if we present them with many alternative options.
2. It's easier to find help if everyone had the same set up.
3. Alternative set-ups make it difficult to know if errors are due to bad set up, or something actually wrong with the service.
4. If the service set up is standardized, then people will be more proactive about maintaining the set up documentation, rather than deferring it believing that it's only an isolated "local set up problem". Problems are more likely to be raised and fixed.

That said, I think moving the database to Docker is the right move. Docker makes it easier to:

1. destroy + recreate a database on whim (i.e can be more experimental with testing migrations and other stuff)
2. isolate your Postgres database (i.e. will there be potentially a naming conflict with database, schema or user?)
3. easily allow for varying different Postgres versions on the same machine (i.e. services depending on different versions of Postgres can have the version that makes the most sense for that service). 

tl;dr is that we should stick with one set up, and that we should use Docker for bootstrapping any service resources if possible.

2023-07-26 23:28 UTC, tiftran commented on docs/quickStart.md
> +or their EDB installer client.  Make sure to install version 14.7, or equivalent, and have
Oh, I meant I agree that there should be one set up method in our docs. I double checked, the docker compose file still works for me. 

As a aside, I think engineers being able to customize their set up is an interesting topic that could be discussed in our next 1:1? (or as a team), but I don't think it blocks this PR.

2023-07-27 15:12 UTC, mtbottle commented on docs/quickStart.md
> +or their EDB installer client.  Make sure to install version 14.7, or equivalent, and have
>  I think engineers being able to customize their set up is an interesting topic that could be discussed in our next 1:1? (or as a team?)

Interesting! I've added it as an agenda item for our tech sync up. Good idea thanks! 😄

2023-07-28 14:13 UTC, taddes commented on docs/quickStart.md
> +or their EDB installer client.  Make sure to install version 14.7, or equivalent, and have
Agreed! Sounds great to me @mtbottle & @tiftran. Given our meeting discussion, I'll make the changes so we opt for the Docker setup and will remove the other alternate/superfluous steps here. I'll just check to make sure there aren't any caveats with the Docker setup we need to annotate.

2023-08-03 19:15 UTC, mtbottle approved these changes
Just a few minor comment, but feel free to merge once they're addressed! Thanks for making the instructions clearer 🚀 :shipit:

2023-08-03 19:15 UTC, mtbottle commented on docs/quickStart.md
> +# pyenv verison install
```suggestion
# pyenv version install
```

2023-08-03 19:15 UTC, mtbottle commented on docs/UserGuide.md
> +If changes need to be undone, one would have to manually revert the advertiser information and create a new snapshot.
No actions necessary but just a note: We can probably like the runbook here once it's written.

2023-08-03 19:15 UTC, mtbottle commented on docs/intro.md
> +    GCP -..- |Periodic sync for<br/>tile information| Contile{Contile}
Let's use the same shape for the services (Shepherd and Contile).
```suggestion
    GCP -..- |Periodic sync for<br/>tile information| Contile(Contile)
```

2023-08-03 20:10 UTC, taddes commented on docs/intro.md
> +    GCP -..- |Periodic sync for<br/>tile information| Contile{Contile}
Thanks @mtbottle ! 🚀

2023-08-03 20:13 UTC, merged