[CONSVC-1346]feat: validation for advertiser urls
mozilla-services/consvc-shepherd pull request #18
Opened 2022-03-22 04:31 UTC by tiftran

2022-03-22 14:13 UTC, ncloudioj requested changes

2022-03-22 14:13 UTC, ncloudioj commented on consvc_shepherd/models/contile.py
> +        if self.get_matching_display() == "prefix" and self.path.endswith("/"):
I think we always require the prefix paths to end with "/" in [Contile](https://github.com/mozilla-services/contile/blob/main/src/adm/settings.rs#L58-L59).

2022-03-22 14:13 UTC, ncloudioj commented on consvc_shepherd/models/contile.py
> +    domain = models.CharField(max_length=80)
Nit: per [Wikipedia](https://en.wikipedia.org/wiki/Hostname), the length of hostname could go up to 253 ASCII characters.

2022-03-22 14:13 UTC, ncloudioj commented on consvc_shepherd/models/contile.py
> +    if not all([h.isalnum() or h in [".", "-"] for h in host]) or "." not in host:
I think we can also check the total number of dots in the hostname. Should be either 1 or 2 dots to cover both `{leaf-domain}.{second-level-domain}.{top-domain}` and `{second-level-domain}.{top-domain}`.

2022-03-22 14:13 UTC, ncloudioj commented on consvc_shepherd/models/contile.py
> +        if self.get_matching_display() == "prefix" and self.path.endswith("/"):
Let's also update all the unit tests below to reflect that.

2022-03-22 18:23 UTC, jrconlin commented on consvc_shepherd/models/contile.py
> +    domain = models.CharField(max_length=80)
IIRC, [RFC 2181](https://datatracker.ietf.org/doc/html/rfc2181#section-11) says that a max Fully Qualified Domain Name length of 255 octets, including the full stops `.` (one octet = one traditional 8 bit byte character). This should also cover IDNA entries as well, if we ever get those.

2022-03-22 23:24 UTC, ncloudioj commented on consvc_shepherd/models/contile.py
> +            f"{host}: hostnames should have the structure <leaf-domain>.<second-level-domain>.<top-domain> and <second-level-domain>.<top-domain>"
```suggestion
            f"{host}: hostnames should have the structure <leaf-domain>.<second-level-domain>.<top-domain> or <second-level-domain>.<top-domain>"
```

2022-03-22 23:26 UTC, ncloudioj commented on consvc_shepherd/migrations/0003_alter_advertiserurl_domain.py
> +            field=models.CharField(max_length=253),
As @jrconlin pointed out, let's do 255 (253 + 2 dots) here :)

2022-03-22 23:27 UTC, ncloudioj commented on consvc_shepherd/models/contile.py
> +    domain = models.CharField(max_length=253)
As @jrconlin pointed out, let's do 255 (253 + 2 dots) here :)

2022-03-23 00:21 UTC, ncloudioj commented on consvc_shepherd/tests/test_models_contile.py
> +    def test_ad_url_with_valid_exact_saves_correctly(self):
For completeness, could you add another test case to ensure FQDNs (e.g. `www.example.com`) are accepted?

2022-03-23 00:22 UTC, ncloudioj approved these changes
r+ with a few more nits.

Looks great, thanks!

2022-03-23 03:16 UTC, tiftran commented on consvc_shepherd/models/contile.py
> +    domain = models.CharField(max_length=253)
eek! didnt see @jrconlin's comment, yes will do!

2022-03-23 05:06 UTC, tiftran commented on consvc_shepherd/models/contile.py
> +            f"{host}: hostnames should have the structure <leaf-domain>.<second-level-domain>.<top-domain> and <second-level-domain>.<top-domain>"
ugh... english is hard 😅

2022-03-23 05:27 UTC, merged