[AE-565] Fetch and save the country for products after creating a new country field in the BoostrProduct table
mozilla-services/consvc-shepherd pull request #241
Opened 2024-09-09 20:29 UTC by akhan-mozilla

## References

JIRA: [AE-565](https://mozilla-hub.atlassian.net/browse/AE-565)

## Description
1. Added a new country column to the BoostrProducts table.
2. Added a function to the Boostr script file to fetch and save the country code in the table, based on possible country codes that we might receive from the Boostr API.

## PR Review Checklist

_Put an `x` in the boxes that apply_

- [ ] This PR conforms to the [Contribution Guidelines](https://github.com/mozilla-services/consvc-shepherd/blob/main/CONTRIBUTING.md).
- [ ] The PR title starts with the JIRA issue reference, format `[DISCO-####]`, and has the same title (if applicable).
- [ ] [Documentation](https://github.com/mozilla-services/consvc-shepherd/tree/main/docs) has been updated (if applicable).
- [ ] Functional and performance test coverage has been expanded and maintained (if applicable).

2024-09-09 21:10 UTC, nanagb requested changes

2024-09-09 21:10 UTC, nanagb commented on consvc_shepherd/migrations/0010_boostrproduct_country.py
> +            field=models.CharField(blank=True),
We can use [choices](https://docs.djangoproject.com/en/5.1/ref/models/fields/#choices) here

2024-09-09 22:05 UTC, akhan-mozilla commented on consvc_shepherd/management/commands/sync_boostr_data.py
> +    country_codes = ["US", "UK", "DE", "FR", "CA", "IT", "SP"]
Understood. For SP, it appears to also be used for Spain. I will keep it in the list for now; however, I will update the list once confirmed by the Ad Ops team.

2024-09-09 22:06 UTC, akhan-mozilla commented on consvc_shepherd/migrations/0010_boostrproduct_country.py
> +            field=models.CharField(blank=True),
Thanks for pointing this out. I've made the change.

2024-09-09 22:27 UTC, nanagb commented on consvc_shepherd/management/commands/sync_boostr_data.py
> +    country_found = "ES"
`country_found = "ES"` Will still save ES as the country if no match is found in the list. Use `    country_found = ""`

2024-09-09 22:58 UTC, nanagb commented on consvc_shepherd/models.py
I would like to see something on our end that standardizes  how incorrectly entered country codes in Boostr is stored in our shepherd db. This will ensure that when we do country breakdowns for reporting, it's accurate and not split into two. eg UK and GB. SP and ES. etc

2024-09-10 16:53 UTC, nanagb approved these changes

2024-09-10 16:58 UTC, merged