Rate limit adjusted GET & POST using retry-after header info
mozilla-services/consvc-shepherd pull request #249
Opened 2024-09-13 15:39 UTC by nanagb

## References

[SHEP-27](https://mozilla-hub.atlassian.net/browse/SHEP-27)

## Problem Statement

Boostr's API has a 100 reqs per min rate limit that's inadequate for our syncing needs. During full syncs, we experience rate limits (429 errors). Our initial solution to introduce rests between each call  didn't always work. Likely due to how rate limits are handled by the Boostr API. 

## Proposed Changes

The 429 response includes a Retry-After header with the number of seconds to wait for before retrying. The new POST and GET functions uses this to determine how long to wait before retrying the sync. An extra second is added to the Retry-After time as an extra precaution. If no value is readable from the header, it will retry again in 60 seconds, which is enough time for the rate limit counter to fully reset.

## Verification Steps

Clear your DB tables and do a full sync (Approx run time should be 3.5 to 4 mins). If successful, there will be no 429 errors in the logs.

2024-09-13 18:17 UTC, mashalifshin commented on consvc_shepherd/management/commands/sync_boostr_data.py
> +
It looks like we are no longer sleeping between requests at all, which is great because the script goes so much faster! 

But as part of this PR, we also need to remove everything related to the request rate interval (the default constant, the config option, the parameter to the script, and the instance variable in the `BoostrApi` class, and all the documentation about it). We don't want to leave around an option that does nothing.

I think we'll also want a PR against [the cron job in the cloud infra repo](https://github.com/mozilla-services/cloudops-infra/blob/master/projects/topsites/k8s/charts/shepherd/values.yaml) to remove that option from the invocation of the script, and maybe some updates to values?. We may want to merge that change before we merge this PR where we remove it entirely (if we think the cron will error when passed a non-existent option, we can check on this locally).

2024-09-13 18:30 UTC, mashalifshin requested changes
Thanks so much for peeling this off into its own PR, super helpful! And for making the fix, I ran it locally and this approach is working much better than trying to wait between requests!

To make this merge-able there is a bit more work to do on adding specs and cleaning up the request rate interval option that got disabled (both here and in the cloudops infra repo). Also needs a new test verifying the 429 handling behavior. Details in the comments.

2024-09-13 18:30 UTC, mashalifshin commented on consvc_shepherd/management/commands/sync_boostr_data.py
> +    def post(self, path: str, json=None, headers=None) -> Any:
Still a python newbie, can you help me understand the change here and related change below to set the json param to `{}` when it's `None`? I thought that specifying the parameter with the equals sign like `json={}` makes `{}` the default value for `json` if nothing is passed in? Am I missing something?

2024-09-13 18:30 UTC, mashalifshin commented on consvc_shepherd/management/commands/sync_boostr_data.py
> +        if response.status_code == 429:
Could we add a debug log here that we received the 429, and what the wait time is?

2024-09-13 18:30 UTC, mashalifshin commented on consvc_shepherd/management/commands/sync_boostr_data.py
> +            return self.get(path, params, headers)
I think I'm confused by the control flow here? Is there a reason we're returning this instead of doing something like 

```python
response  = self.get(path, params, headers)
```

Also you can use `self.session.get` here, which automatically holds the auth headers. I don't think it actually matters since we're also passing the auth headers explicitly, but it's just nice to be consistent

2024-09-13 18:30 UTC, mashalifshin commented on consvc_shepherd/tests/test_sync_boostr.py
>  class TestSyncBoostrData(TestCase):
I think we need to add a new test here that verifies the correct handling of 429 responses. Lmk if you want to pair or if I can support you in creating that in some other way. We'd want a new kind of MockResponse that returns a 429, and then we can assert that the sleep function was called with the right amount of time.

2024-09-13 18:32 UTC, mashalifshin commented
Oh yes and don't forget to add [SHEP-27] to the title of the PR (check out `git log --oneline` to see how nice this comes out in the repo history).

2024-09-13 19:38 UTC, nanagb commented on consvc_shepherd/management/commands/sync_boostr_data.py
> +    def post(self, path: str, json=None, headers=None) -> Any:
I also recently discovered this. But basically default params are evaluated once when function definitions are evaluated and not every time the function is called. So when you have a mutable such as a dict or list it can cause issues because it holds onto old values during subsequent calls.

There are two helpful posts here:
[https://web.archive.org/web/20200221224620id_/http://effbot.org/zone/default-values.htm](https://web.archive.org/web/20200221224620id_/http://effbot.org/zone/default-values.htm)
[https://docs.python.org/3/reference/compound_stmts.html#function-definitions ](https://docs.python.org/3/reference/compound_stmts.html#function-definitions ) Read the section titled **"Default parameter values are evaluated from left to right when the function definition is executed."**

2024-09-13 20:40 UTC, nanagb commented on consvc_shepherd/management/commands/sync_boostr_data.py
> +        if response.status_code == 429:
Done

2024-09-13 20:54 UTC, nanagb commented on consvc_shepherd/management/commands/sync_boostr_data.py
> +            return self.get(path, params, headers)
It's a recursive call to make sure all the logic around 429 errors are applied with each attempt. `self.session.get` would not handle a 429 that gets thrown right after sleeping. This could happen if some other process triggered a new 429 during the sleep.

2024-09-13 21:01 UTC, nanagb commented on consvc_shepherd/management/commands/sync_boostr_data.py
> +            return self.get(path, params, headers)
`response  = self.get(path, params, headers)` also works I just used return to skip the extra step of returning the response

2024-09-13 21:02 UTC, nanagb commented on consvc_shepherd/tests/test_sync_boostr.py
>  class TestSyncBoostrData(TestCase):
Taking a first pass at it, I'll ping you if I hit a roadblock.

2024-09-13 21:03 UTC, nanagb commented on consvc_shepherd/management/commands/sync_boostr_data.py
> +        if response.status_code == 429:
Done. I removed it right before my commit 😃

2024-09-18 19:46 UTC, nanagb commented on consvc_shepherd/management/commands/sync_boostr_data.py
> +        if response.status_code == 429:
Sounds like a great idea, I'll make that mod

2024-09-18 19:53 UTC, nanagb commented on consvc_shepherd/management/commands/sync_boostr_data.py
> +        if json is None:
Good call, editing

2024-09-18 20:00 UTC, nanagb commented on consvc_shepherd/management/commands/sync_boostr_data.py
> +                f"{self.base_url}/{path}", params=params, headers=headers, timeout=15
Done ty

2024-09-18 22:12 UTC, nanagb commented on consvc_shepherd/management/commands/sync_boostr_data.py
> +    def post(self, path: str, json=None, headers=None) -> Any:
@cyptm No I didn't see it, but based on the documented behavior and our code, we likely would have been affected. As mentioned, I stumbled upon this, I think it popped up while testing out the ruff linter, so I went searching for why this was such a big deal.

2024-09-20 00:14 UTC, mashalifshin reviewed
Nana it works really well!!!!!! Was able to run a full sync successfully in ~23 minutes.  🙌

![the-rock-snl-hahaha-it-works](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExZGM3MTB1dzdwc3hmZnhybWEyajMxNmprdzRvNmYxdTFscjQxYjJ3cCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/xUA7b2cALb4TaV1ECA/giphy.gif)

Though I did not encounter any connection closed or timeout issues this run, just the rate limits response, so not sure how it would work with that.

There are a lot of comments here but the main points are that to be ready for merge, this PR needs some better testing of the various possibilities/branches in the retry code, and ideally we would clean up the retry control flow since it's hard to reason about and also hard to test.

I know I wrote a lot of text, but I'm just trying to be as helpful as I can. Lmk if pairing or talking it over would work better for you.

2024-09-20 00:14 UTC, mashalifshin commented on consvc_shepherd/management/commands/sync_boostr_data.py
> +                self.log.info(f"{e}: Read timeout Current Retry: {current_retry}")
Let's remove the "read timeout" part of this log, because it could be any sort of exception thrown from requests that is being handled here, not just the read timeout, right?

2024-09-20 00:23 UTC, nanagb commented on Makefile
> +	$(POETRY) run mypy $(APP_DIRS) --config-file="pyproject.toml"
I agree with your point. We can do it either way, I think it makes sense to move it to a separate PR.

One reason it's here is because `make ruff` is not officially part of any of the automated linting we are doing in CI/CD.  `mypy` is already part of the commands we have in `make lint` and `make lint-fix` so I added it because it was missing.

2024-09-20 00:58 UTC, nanagb commented on consvc_shepherd/management/commands/sync_boostr_data.py
> +    def post(self, path: str, json=None, headers=None) -> Any:
@mashalifshin Based on my understand of how this works, this is the line that could have been a potential cause of bugs https://github.com/mozilla-services/consvc-shepherd/blob/df3f3a2906183a81f12f9f1e0ca3890b4b48c09d/consvc_shepherd/management/commands/sync_boostr_data.py#L164

2024-09-20 01:19 UTC, nanagb commented on consvc_shepherd/management/commands/sync_boostr_data.py
> +        except requests.exceptions.RequestException as e:
Yes correct for both comments. I thought about having rate limits and the timeouts having their own retries, but in the worst case that could end up with a get request that take more than 5 mins to complete. If somehow multiple requests end up in this situation, I can see it taking multiple hours or days to run a sync.

2024-09-20 01:35 UTC, nanagb commented on consvc_shepherd/management/commands/sync_boostr_data.py
> +                        f"{response.status_code}: Rate Limited - Waiting {retry_after} seconds. \
Yep not the intended result. I was formatting the line for the linter because it was over 120 chars. Fixed now

2024-09-20 01:37 UTC, nanagb commented on consvc_shepherd/management/commands/sync_boostr_data.py
> +                self.log.info(f"{e}: Read timeout Current Retry: {current_retry}")
Yes, this is a generic exception for multiple types of errors. Fixed

2024-09-20 01:45 UTC, nanagb commented on consvc_shepherd/tests/test_sync_boostr.py
> +    def test429(self, mock_post, mock_get):
I'll make some more mods to this test and check in with you tomorrow to setup a time to pair and review. Thanks

2024-09-23 23:02 UTC, mashalifshin commented on consvc_shepherd/management/commands/sync_boostr_data.py
> -            default=REQUEST_INTERVAL_SECONDS_DEFAULT,
Good find, thank you!

2024-09-27 18:47 UTC, mashalifshin approved these changes
🚢 Well tested!!! Thank you

2024-09-27 19:27 UTC, merged