[SHEP-17] Add BQ data fetcher script
mozilla-services/consvc-shepherd pull request #264
Opened 2024-09-26 16:59 UTC by kauana

## References

[SHEP-17](https://mozilla-hub.atlassian.net/browse/SHEP-17)

## Problem Statement

We want to be able to pull some Kevel metadata from BigQuery to display in on the Shepherd UI. This script retrieves selected ad data from BigQuery and inserts it into Shepherd DB. Once configured, this script will run daily, fetching Kevel metadata for flights.

## Proposed Changes

- **Add the "fetch_bq_data" script**: This script will use the BigQuery client to query Kevel metadata in BigQuery. If the data is successfully fetched, it will be inserted into the Shepherd database. If the script runs again, it will update the click and impression data for flights rather than creating new rows in the db.
- **Add unit tests for the fetch_bq_data script**: Ensure that the functions in the script are behaving correctly.

## Verification Steps

**Note**: This script includes a field (`flight_name`) that is not yet available in BigQuery. As a result, running the script as is will cause an error because the BigQuery client won't find the flight name. I’m coordinating with Curtis to get this field added, but in the meantime, to test the script, we can comment out or delete the `flight_name` field from the queries in this script.

To manually run and test the script:

1. Start Shepherd with `docker compose up --build`.
2. Exec into the Shepherd container with `make debug`.
3. Pass your gcloud credentials to the shep container to access the BigQuery view `moz-fx-data-shared-prod.ads.consolidated_ad_metrics_daily_pt`:
    1. Login to gcloud locally `gcloud auth application-default login`.
    2. Copy your gcloud creds into the shepherd container:
   ```bash
   docker cp ~/.config/gcloud/application_default_credentials.json consvc-shepherd-app-1:/app/application_default_credentials.json
   
   export GOOGLE_APPLICATION_CREDENTIALS="/app/application_default_credentials.json"

   ```
4. Run the script. Note that date is optional and defaults to today's date.
    ```bash
    python manage.py fetch_bq_data --project_id "moz-fx-ads-nonprod" --date $(date +%F)
    ```
    
    If successful you should see: `BigQuery fetch completed for data <today's date>`.
5. Now the `consvc_deliveredflight` db table was populated with click and impression data. You can verify this by checking the table in PostgreSQL (exec into `db-1` container), or by viewing the Delivered Flights tab in the admin interface

6. Last but no least, run the tests and ensure they pass.

2024-09-26 17:39 UTC, kauana commented on consvc_shepherd/management/commands/fetch_bq_data.py
> +                country,
Hmm, I'm grouping by country here, but after playing around with the data returned, some flights are in A LOT of countries (see image below). I'm wondering dropping country so we don't have so many entries for the same flight
![image](https://github.com/user-attachments/assets/e60b363b-ece1-4c90-9500-ed16f51fcdc0)

2024-09-27 19:27 UTC, mashalifshin commented
I haven't taken this for a test drive yet, but just wanted to share an idea with you and get your thoughts. 

Reasoning from what we ended up doing for the Boostr script, do we want to store some metadata about this script's runs? What do you think about generalizing the `boostr_sync_status` table into something that's a more general `data_sync_statuses` with a new `sync_type` field for these different kinds of jobs? Or maybe it's better un-generalized, with two separate tables like `boostr_sync_status` and `bq_sync_status`?

I think this idea might a bigger lift and a bit out of scope of this PR, so it could be a totally separate PR and/or ticket....

2024-09-27 19:44 UTC, kauana commented
> I haven't taken this for a test drive yet, but just wanted to share an idea with you and get your thoughts.
> 
> Reasoning from what we ended up doing for the Boostr script, do we want to store some metadata about this script's runs? What do you think about generalizing the `boostr_sync_status` table into something that's a more general `data_sync_statuses` with a new `sync_type` field for these different kinds of jobs? Or maybe it's better un-generalized, with two separate tables like `boostr_sync_status` and `bq_sync_status`?
> 
> I think this idea might a bigger lift and a bit out of scope of this PR, so it could be a totally separate PR and/or ticket....

I like the idea of a separate table `bq_sync_status` to record the history of status of the fetch_bq_data script. In fact, I will go ahead and create a story for this

2024-10-02 00:00 UTC, mashalifshin requested changes
This code looks so nice and clean! I appreciate the attention to the tests! 👩‍🍳🤌💋 

Before merge, would you please
1. Update the `/docs` folder with a new `.md` file about this sync script? The instructions you have on the PR for running locally are a great starting point, I tried those and they work great except a small typo `fetch_bq_data` -> `sync_bq_data`
2. The script as written currently fails because `flight_name` doesn't exist yet in BQ. I think probably easiest way to go forward is to remove `flight_name` from the PR for now, so the script can run successfully on `main`. And then once we get that field in BQ, we make a new PR that uses the `update_or_create` functionality to upsert `flight_name`. I guess there are other ways to handle this like you could have a case to handle its absence in this code, totally open to whatever approach you prefer.
3. Seeing an error when I try to run this. Could be on my end since I might have botched something commenting out `flight_name`, but here's the stack trace:

```sh
Starting BigQuery sync for date 2024-10-01
/usr/local/lib/python3.11/site-packages/google/cloud/bigquery/table.py:1727: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(
BigQuery sync process has encounterd an error: Exception: Field 'campaign_id' expected a number but got <NA>. Trace: Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/db/models/fields/__init__.py", line 2053, in get_prep_value
    return int(value)
           ^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NAType'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/consvc_shepherd/management/commands/sync_bq_data.py", line 157, in sync_data
    self.upsert_data(df)
  File "/app/consvc_shepherd/management/commands/sync_bq_data.py", line 133, in upsert_data
    delivered_flight, created = DeliveredFlight.objects.update_or_create(
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 949, in update_or_create
    obj, created = self.select_for_update().get_or_create(defaults, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 916, in get_or_create
    return self.get(**kwargs), False
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 623, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1546, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1577, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1492, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1319, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/lookups.py", line 341, in get_prep_lookup
    return super().get_prep_lookup()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/lookups.py", line 85, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/fields/__init__.py", line 2055, in get_prep_value
    raise e.__class__(
TypeError: Field 'campaign_id' expected a number but got <NA>.

CommandError: An error occurred: Field 'campaign_id' expected a number but got <NA>.
```

2024-10-02 00:03 UTC, mashalifshin commented on consvc_shepherd/management/commands/fetch_bq_data.py
> +                country,
I think this is the right call. My understanding is still vague here but ad ops team is currently using the Boostr Product to set up countries targeting, so we'll probably be grouping/sorting by the country data that's in the Campaign instead of the info coming from BQ, until we can do better country targeting e2e.

2024-10-02 00:06 UTC, mashalifshin commented
Oh yes forgot to mention the `Makefile` has helpful commands to generate and view the docs `doc-install-deps`, `doc`, and `doc-preview`

2024-10-02 03:46 UTC, kauana commented on consvc_shepherd/migrations/0017_remove_deliveredflight_unique_delivered_flight_and_more.py
> +# Generated by Django 4.2.16 on 2024-09-26 20:53
1. I've added the docs for the sync bq data script and the cronjob that will run it. I've tried running `make doc-preview` but I can't see the new docs showing in the Shepherd docs. I also ran `make doc` without any issues. Am I missing something? 🤔 
2. That's a good idea. I've removed flight name temporarily so we can merge this without commenting anything. Once Curtis makes the PR on his side I will raise a PR to add flight name again.
3. No, this wasn't on your end. We should be filtering by campaign_ids that aren't null so I updated the code accordingly. Good catch!

2024-10-02 19:30 UTC, kauana commented on consvc_shepherd/management/commands/sync_bq_data.py
> +            self.log.warning(f"No data returned for the date {self.date}: {str(ve)}")
That's a good point. I thought about it and we should just log a warning if the data wasn't found. This is because the script captures new flights added for today's date from bigquery. But for the data to show up on BQ in the first place it needs to get ingested from Glean by Snowflake/Bigquery which takes some time(~1-2 hours) to show up, so if we don't find anything yet we should log a warning to let us know, but the script should finish successfully.

2024-10-02 20:55 UTC, mashalifshin approved these changes
Just took it for another spin after the last round of changes -- it works like a charm! I've got `DeliveredFlights` data from BQ!! 🙌 :shipit:

2024-10-02 20:55 UTC, mashalifshin commented on docs/operations/syncBigQueryDataCron.md
> +### Debugging, troubleshooting and viewing logs
I know this isn't DRY but that's okay for now, I'll make a ticket for separating out a markdown file with instructions like these for connecting to and troubleshooting deployed envs ...

2024-10-02 20:55 UTC, mashalifshin commented on docs/operations/syncBigQueryData.md
> +    python manage.py fetch_bq_data --project_id "moz-fx-ads-nonprod" --date $(date +%F)
Typo: `fetch` -> `sync`

2024-10-02 20:55 UTC, mashalifshin commented on consvc_shepherd/migrations/0017_remove_deliveredflight_unique_delivered_flight_and_more.py
> +# Generated by Django 4.2.16 on 2024-09-26 20:53
1. Did you run `doc-install-deps` before running `make doc` and `make doc-preview`? If so, then I don't know what's going on there. I think it's okay to merge without previewing, check in the deployed env (they end up served here: https://mozilla-services.github.io/consvc-shepherd/operations/index.html), and make follow-up PRs to fix. 

(For me, the preview command serves the docs and opens a browser at http://localhost:3000/ . Another tricky thing is that by default the table of contents side panel is closed, so you'll want to hit the hamburger menu on the upper left to open).

2. Nice, thank you for doing that. 

3. Sweet, thanks for the fix and glad we caught a bug before it hit `main`. Embodying some of the deep value of code reviews rn! 🙌

2024-10-03 02:28 UTC, merged